# Generated by Django 5.2.1 on 2025-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_orders',
            field=models.IntegerField(default=1, verbose_name='available orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_products',
            field=models.IntegerField(default=1, verbose_name='available products'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_orders',
            field=models.IntegerField(default=1, verbose_name='max orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_products',
            field=models.IntegerField(default=1, verbose_name='max products'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller')], default='seller', max_length=11, verbose_name='role'),
        ),
    ]
