# Generated by Django 5.2.1 on 2025-07-05 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_userprofile_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
