# Generated by Django 5.2.1 on 2025-06-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_export_data',
            new_name='can_import',
        ),
    ]
