# Generated by Django 5.2.1 on 2025-06-07 18:53

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event_plan', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('location', models.CharField(choices=[(1, 'Adrar'), (2, 'Chlef'), (3, 'Laghouat'), (4, 'Oum El Bouaghi'), (5, 'Batna'), (6, 'Béjaïa'), (7, 'Biskra'), (8, 'Béchar'), (9, 'Blida'), (10, 'Bouira'), (11, 'Tamanrasset'), (12, 'Tébessa'), (13, 'Tlemcen'), (14, 'Tiaret'), (15, 'Tizi Ouzou'), (16, 'Algiers'), (17, 'Djelfa'), (18, 'Jijel'), (19, 'Sétif'), (20, 'Saïda'), (21, 'Skikda'), (22, 'Sidi Bel Abbès'), (23, 'Annaba'), (24, 'Guelma'), (25, 'Constantine'), (26, 'Médéa'), (27, 'Mostaganem'), (28, "M'Sila"), (29, 'Mascara'), (30, 'Ouargla'), (31, 'Oran'), (32, 'El Bayadh'), (33, 'Illizi'), (34, 'Bordj Bou Arréridj'), (35, 'Boumerdès'), (36, 'El Tarf'), (37, 'Tindouf'), (38, 'Tissemsilt'), (39, 'El Oued'), (40, 'Khenchela'), (41, 'Souk Ahras'), (42, 'Tipaza'), (43, 'Mila'), (44, 'Aïn Defla'), (45, 'Naâma'), (46, 'Aïn Témouchent'), (47, 'Ghardaïa'), (48, 'Relizane'), (49, 'Timimoun'), (50, 'Bordj Badji Mokhtar'), (51, 'Ouled Djellal'), (52, 'Béni Abbès'), (53, 'In Salah'), (54, 'In Guezzam'), (55, 'Touggourt'), (56, 'Djanet'), (57, "El M'Ghair"), (58, 'El Menia')], max_length=100)),
                ('category', models.CharField(choices=[(1, 'Entertainment and Music'), (2, 'Business and Professional Development'), (3, 'Culture, Arts and Film Screenings'), (4, 'Food and Beverages'), (5, 'Sports and Health'), (6, 'Technology and Innovation'), (7, 'Travel and Adventure'), (8, 'General and Entertainment'), (9, 'Religious Events'), (10, 'Environmental and Sustainability Events'), (11, 'Academic and Educational Events'), (12, 'Fashion and Beauty'), (13, 'Nightlife'), (14, 'Appointments')], max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('vip_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('children_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('children_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
