# Generated by Django 5.2.1 on 2025-06-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_is_approved_event_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
